#! /usr/bin/python

import os
import time
from subprocess import Popen
import platform


def execAndWait(cli_str):
    print '    EXEC:', cli_str
    process = Popen(cli_str, shell=True)
    while process.poll() is None:
        time.sleep(0.01)


perm_app_register = False
try:
    dist, version, ID = platform.linux_distribution()
    major, minor = [int(v) for v in version.split('.')][:2]
    if dist == 'Ubuntu' and ((major, minor) == (10, 10) or major >= 11):
        perm_app_register = True
except:
    pass


def createDesktopFile(name, idstr, arglist, toDir=''):
    toPath = os.path.join(toDir, 'kissync.desktop')
    deskfile = open(toPath, 'w')
    deskfile.write('[Desktop Entry]\n')
    deskfile.write('Type=Application\n')
    deskfile.write('Name=Kissync')
    if name:
        deskfile.write(' (' + name + ')')
    deskfile.write('\n')
    deskfile.write('GenericName=Kissync Cloud Synchronizer\n')
    deskfile.write('Comment=A cloud synchronizer with SmartFile\n')
    deskfile.write('Categories=Network;\n')
    deskfile.write('Exec=python /usr/share/kissync/main.py')
    for a in arglist:
        deskfile.write(' --%s' % a)
    if perm_app_register:
        deskfile.write(' %u')
    deskfile.write('\n')
    deskfile.write('Icon=kissyncicon\n')
    deskfile.write('StartupNotify=false\n')
    deskfile.write('Terminal=false\n')
    deskfile.close()


time.sleep(1)
createDesktopFile('', '', [], '/usr/share/applications')

print '   Setting up menu items.'
execAndWait(
    'xdg-icon-resource install --novendor --context apps --size 64 /usr/share/kissync/ui/images/menuicon.png kissyncicon')
execAndWait('xdg-desktop-menu  install --novendor /usr/share/applications/armory.desktop')
print ''
print 'Kissync was installed successfully!'
print ''
