#! /usr/bin/python

import time
from subprocess import Popen


def execAndWait(cli_str):
    print '\tEXEC:', cli_str
    process = Popen(cli_str, shell=True)
    while process.poll() is None:
        time.sleep(0.01)


execAndWait('xdg-desktop-menu  uninstall /usr/share/applications/kissync.desktop')
execAndWait('xdg-icon-resource uninstall --size 64 kissyncicon')
